services:
  zigbee2mqtt:
    container_name: ${APP_NAME}-zigbee2mqtt
    restart: unless-stopped
    image: koenkk/zigbee2mqtt
    depends_on:
      - mosquitto
    volumes:
      - ./docker/zigbee2mqtt/config/secret.yaml:/app/data/secret.yaml
      - ./docker/zigbee2mqtt/config/configuration.yaml:/app/data/configuration.yaml
      - ./docker/zigbee2mqtt/volume/data:/app/data
      - /run/udev:/run/udev:ro
    ports:
      - "8080:8080"
    environment:
      - TZ=Europe/Paris
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
