parameters:
    zigbee2mqtt_reference: 'zigbee2mqtt'
    plugin_requirements:
        - mqtt
    mqtt_host: '%env(MQTT_HOST)%'
    mqtt_port: '%env(MQTT_PORT)%'
    mqtt_user: '%env(MQTT_USER)%'
    mqtt_password: '%env(MQTT_PASSWORD)%'
    mqtt_client_id: '%env(MQTT_CLIENT_ID)%'
    mqtt_version: '%env(MQTT_VERSION)%'
    mqtt_base_topic: 'zigbee2mqtt2marvin'
    exclude_topics:
        - 'zigbee2mqtt2marvin/bridge/definitions'
        - 'zigbee2mqtt2marvin/bridge/extensions'

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    EnderLab\Zigbee2mqttBundle\:
        resource: '../src/'
